apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: production
  labels:
    app: hello-api
    environment: production

spec:
  replicas: 3
  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: hello-api
      environment: production

  template:
    metadata:
      labels:
        app: hello-api
        environment: production

    spec:
      containers:
        - name: hello-api
          image: saiprathapk17/hello-api:2.0.0
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hello-api
  namespace: production
  labels:
    app: hello-api
    environment: production

spec:
  type: ClusterIP

  selector:
    app: hello-api
    environment: production

  ports:
    - name: http
      port: 80
      targetPort: 8000